export const ADD_CARD="ADD_CARD";
export const DELETE_CARD="DELETE_CARD";
export const INCREASE_QUANTITY="INCREASE_QUANTITY";
export const DECREASE_QUANTITY="DECREASE_QUANTITY";
export const DELETE_ALL_CARDS="DELETE_ALL_CARDS";
